CREATE TABLE PUBLIC.ARTICLE_JS_RESOURCES
(
    ARTICLE_ID      BIGINT       NOT NULL,
    EXECUTION_ORDER INTEGER DEFAULT 0,
    RESOURCE        VARCHAR(255) NOT NULL
);
ALTER TABLE ARTICLE_JS_RESOURCES
    ADD CONSTRAINT FK_ARTICLE_JS_RESOURCES_ARTICLE_ID
        FOREIGN KEY (ARTICLE_ID)
            REFERENCES PUBLIC.ARTICLE (ID);

CREATE INDEX FK_ARTICLE_JS_RESOURCES_ARTICLE_ID_INDEX ON PUBLIC.ARTICLE_JS_RESOURCES (ARTICLE_ID);

INSERT INTO ARTICLE_JS_RESOURCES (ARTICLE_ID, EXECUTION_ORDER, RESOURCE)
SELECT AJ.ARTICLE_ID AS ARTICLE_ID, J.EXECUTIONORDER AS EXECUTION_ORDER, J.NAME AS RESOURCE
FROM ARTICLE_ARTICLE_JS_RESOURCE AJ
         JOIN ARTICLE_JS_RESOURCE J ON AJ.PLUGINJSRESOURCES_ID = J.ID;

DROP TABLE ARTICLE_ARTICLE_JS_RESOURCE;
DROP TABLE ARTICLE_JS_RESOURCE;

ALTER TABLE ARTICLE_JS_RESOURCES RENAME TO ARTICLE_JS_RESOURCE;
ALTER TABLE ARTICLE_CSS_RESOURCES RENAME TO ARTICLE_CSS_RESOURCE;
ALTER TABLE ARTICLE_CSS_RESOURCE ALTER COLUMN PLUGINCSSRESOURCES RENAME TO RESOURCE;

CREATE TABLE PUBLIC.ARTICLE_JS_CODE_TMP
(
    ARTICLE_ID      BIGINT              NOT NULL,
    EXECUTION_ORDER INTEGER DEFAULT 0,
    CODE            VARCHAR(1000000000) NOT NULL
);
ALTER TABLE PUBLIC.ARTICLE_JS_CODE_TMP
    ADD CONSTRAINT FK_ARTICLE_JS_CODE_ARTICLE_ID
        FOREIGN KEY (ARTICLE_ID)
            REFERENCES PUBLIC.ARTICLE (ID);
CREATE INDEX FK_ARTICLE_JS_CODE_ARTICLE_ID_INDEX ON PUBLIC.ARTICLE_JS_CODE_TMP (ARTICLE_ID);

INSERT INTO ARTICLE_JS_CODE_TMP (ARTICLE_ID, EXECUTION_ORDER, CODE)
SELECT AJ.ARTICLE_ID AS ARTICLE_ID, J.EXECUTIONORDER AS EXECUTION_ORDER, J.CONTENT AS CODE
FROM ARTICLE_ARTICLE_JS_CODE AJ
         JOIN ARTICLE_JS_CODE J ON AJ.PLUGINJSCODES_ID = J.ID;

DROP TABLE ARTICLE_ARTICLE_JS_CODE;
DROP TABLE ARTICLE_JS_CODE;

ALTER TABLE ARTICLE_JS_CODE_TMP RENAME TO ARTICLE_JS_CODE;

ALTER TABLE ARTICLE_CSS_RESOURCE DROP CONSTRAINT FKDHXLRP9K9LIQ0LLMCRNHDPNTR;
ALTER TABLE ARTICLE_CSS_RESOURCE DROP CONSTRAINT FK13920B00997E397F;

ALTER TABLE ARTICLE_CSS_RESOURCE
    ADD CONSTRAINT FK_ARTICLE_CSS_RESOURCE_ARTICLE_ID
        FOREIGN KEY (ARTICLE_ID)
            REFERENCES PUBLIC.ARTICLE (ID);

alter table ARTICLE drop CONSTRAINT FKA1PIGU04BX0HMKDL94S7E9G5G;
alter table ARTICLE drop CONSTRAINT FKFF2458D6AE9EE157;

ALTER TABLE ARTICLE
    ADD CONSTRAINT FK_ARTICLE_CONTENTNODE_ID
        FOREIGN KEY (CONTENTNODE_ID)
            REFERENCES PUBLIC.CONTENTNODE (ID);

alter table CONTENTNODE drop CONSTRAINT FKJAE7CHEHT1GEHCT744DBBFCQ;
alter table CONTENTNODE drop CONSTRAINT FK692D91DBEF277C15;
alter table CONTENTNODE drop CONSTRAINT FKG1JWC9FD747BVFV5XPKCIDSMV;
alter table CONTENTNODE drop CONSTRAINT FK692D91DBCBB7E95D;

ALTER TABLE CONTENTNODE
    ADD CONSTRAINT FK_CONTENTNODE_NODE_ID
        FOREIGN KEY (PARENT_ID)
            REFERENCES PUBLIC.NODE (ID);

ALTER TABLE CONTENTNODE
    ADD CONSTRAINT FK_CONTENTNODE_USER_ACCOUNTS_ID
        FOREIGN KEY (AUTHOR_ID)
            REFERENCES PUBLIC.USER_ACCOUNTS (ID);

alter table CONTENTNODE_CONTENT_TAG drop CONSTRAINT FK917UCTC36FRWLXI9ALKYSH9RL;
alter table CONTENTNODE_CONTENT_TAG drop CONSTRAINT FK92945E304E3CB45A;
alter table CONTENTNODE_CONTENT_TAG drop CONSTRAINT FK1P5LSOXUT947I1SI3XL1YRM4U;
alter table CONTENTNODE_CONTENT_TAG drop CONSTRAINT FK92945E3028380FCC;

ALTER TABLE CONTENTNODE_CONTENT_TAG
    ADD CONSTRAINT FK_CONTENTNODE_CONTENT_TAG_CONTENTNODES_ID
        FOREIGN KEY (CONTENTNODES_ID)
            REFERENCES PUBLIC.CONTENTNODE (ID);

ALTER TABLE CONTENTNODE_CONTENT_TAG
    ADD CONSTRAINT FK_CONTENTNODE_CONTENT_TAG_CONTENTTAGS_ID
        FOREIGN KEY (CONTENTTAGS_ID)
            REFERENCES PUBLIC.CONTENT_TAG (ID);

