-- realign duplicities
UPDATE HW_ITEM_TYPE
SET HW_TYPE_ID =
		(SELECT MIN(T1.ID)
		 FROM HW_TYPE T1
				  JOIN HW_TYPE T2 ON T1.NAME = T2.NAME
		 WHERE T2.ID = HW_ITEM_TYPE.HW_TYPE_ID
		 GROUP BY T1.NAME);

-- remove obsolete
DELETE
HW_TYPE WHERE NOT EXISTS (SELECT id FROM HW_ITEM_TYPE hit WHERE hit.HW_TYPE_ID = HW_TYPE.ID);