-- Content node changes

ALTER TABLE CONTENTNODE RENAME TO CONTENT_NODE;

ALTER TABLE CONTENT_NODE ALTER COLUMN CONTENTREADERID RENAME TO CONTENT_READER_ID;
ALTER TABLE CONTENT_NODE ALTER COLUMN CONTENTID RENAME TO CONTENT_ID;
ALTER TABLE CONTENT_NODE ALTER COLUMN CREATIONDATE RENAME TO CREATION_DATE;
ALTER TABLE CONTENT_NODE ALTER COLUMN LASTMODIFICATIONDATE RENAME TO LAST_MODIFICATION_DATE;
ALTER TABLE CONTENT_NODE ALTER COLUMN DRAFTSOURCEID RENAME TO DRAFT_SOURCE_ID;

ALTER TABLE CONTENT_NODE
    ADD COLUMN PUBLICATED_BY_PARENT BOOLEAN;

UPDATE CONTENT_NODE
SET PUBLICATED_BY_PARENT = TRUE;

-- Node changes

ALTER TABLE NODE
    ADD COLUMN PUBLICATED BOOLEAN;

UPDATE NODE
SET PUBLICATED = TRUE;

ALTER TABLE NODE
    ADD COLUMN PUBLICATED_BY_PARENT BOOLEAN;

UPDATE NODE
SET PUBLICATED_BY_PARENT = TRUE;

-- Content tag changes

ALTER TABLE CONTENT_TAG ALTER COLUMN CONTENTNODESCOUNT RENAME TO CONTENT_NODES_COUNT;

-- Content node / Content tag changes

ALTER TABLE CONTENTNODE_CONTENT_TAG RENAME TO CONTENT_NODE_CONTENT_TAG;

ALTER TABLE CONTENT_NODE_CONTENT_TAG ALTER COLUMN CONTENTNODES_ID RENAME TO CONTENT_NODE_ID;
ALTER TABLE CONTENT_NODE_CONTENT_TAG ALTER COLUMN CONTENTTAGS_ID RENAME TO CONTENT_TAG_ID;

UPDATE CONTENT_TAG
SET CONTENT_NODES_COUNT = (SELECT COUNT(*)
                           FROM CONTENT_NODE_CONTENT_TAG
                           WHERE CONTENT_NODE_CONTENT_TAG.CONTENT_TAGS_ID = CONTENT_TAG.ID)

ALTER TABLE CONTENT_NODE_CONTENT_TAG
    ADD CONSTRAINT FK_CONTENT_NODE_CONTENT_TAG_CONTENT_NODES_ID
        FOREIGN KEY (CONTENT_NODES_ID)
            REFERENCES PUBLIC.CONTENT_NODE (ID);

ALTER TABLE CONTENT_NODE_CONTENT_TAG
    ADD CONSTRAINT FK_CONTENT_NODE_CONTENT_TAG_CONTENT_TAGS_ID
        FOREIGN KEY (CONTENT_TAGS_ID)
            REFERENCES PUBLIC.CONTENT_TAG (ID);

-- Print3d changes

ALTER TABLE PRINT3D ALTER COLUMN PROJECTPATH RENAME TO PROJECT_PATH;
ALTER TABLE PRINT3D ALTER COLUMN CONTENTNODE_ID RENAME TO CONTENT_NODE_ID;