CREATE TABLE PUBLIC.ARTICLE_JS_RESOURCES
(
    ARTICLE_ID      BIGINT       NOT NULL,
    EXECUTION_ORDER INTEGER DEFAULT 0,
    RESOURCE        VARCHAR(255) NOT NULL
);
ALTER TABLE PUBLIC.ARTICLE_JS_RESOURCES
    ADD CONSTRAINT FK_ARTICLE_ID
        FOREIGN KEY (ARTICLE_ID)
            REFERENCES PUBLIC.ARTICLE (ID);

CREATE INDEX FK_ARTICLE_ID_INDEX ON PUBLIC.ARTICLE_JS_RESOURCES (ARTICLE_ID);

INSERT INTO ARTICLE_JS_RESOURCES (ARTICLE_ID, EXECUTION_ORDER, RESOURCE)
SELECT AJ.ARTICLE_ID AS ARTICLE_ID, J.EXECUTIONORDER AS EXECUTION_ORDER, J.NAME AS RESOURCE
FROM ARTICLE_ARTICLE_JS_RESOURCE AJ
         JOIN ARTICLE_JS_RESOURCE J ON AJ.PLUGINJSRESOURCES_ID = J.ID;

DROP TABLE ARTICLE_ARTICLE_JS_RESOURCE;
DROP TABLE ARTICLE_JS_RESOURCE;

ALTER TABLE ARTICLE_JS_RESOURCES RENAME TO ARTICLE_JS_RESOURCE;
ALTER TABLE ARTICLE_CSS_RESOURCES RENAME TO ARTICLE_CSS_RESOURCE;
ALTER TABLE ARTICLE_CSS_RESOURCE ALTER COLUMN PLUGINCSSRESOURCES RENAME TO RESOURCE;

CREATE TABLE PUBLIC.ARTICLE_JS_CODE_TMP
(
    ARTICLE_ID      BIGINT              NOT NULL,
    EXECUTION_ORDER INTEGER DEFAULT 0,
    CODE            VARCHAR(1000000000) NOT NULL
);
ALTER TABLE PUBLIC.ARTICLE_JS_CODE_TMP
    ADD CONSTRAINT FK_ARTICLE_ID
        FOREIGN KEY (ARTICLE_ID)
            REFERENCES PUBLIC.ARTICLE (ID);
CREATE INDEX FK_ARTICLE_ID_INDEX ON PUBLIC.ARTICLE_JS_CODE_TMP (ARTICLE_ID);

INSERT INTO ARTICLE_JS_CODE_TMP (ARTICLE_ID, EXECUTION_ORDER, CODE)
SELECT AJ.ARTICLE_ID AS ARTICLE_ID, J.EXECUTIONORDER AS EXECUTION_ORDER, J.CONTENT AS CODE
FROM ARTICLE_ARTICLE_JS_CODE AJ
         JOIN ARTICLE_JS_CODE J ON AJ.PLUGINJSCODES_ID = J.ID;

DROP TABLE ARTICLE_ARTICLE_JS_CODE;
DROP TABLE ARTICLE_JS_CODE;

ALTER TABLE ARTICLE_JS_CODE_TMP RENAME TO ARTICLE_JS_CODE;